export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Home } from './Home'
export { default as JoinUs } from './Join_Us'
export { default as Plans } from './Plans'