const languages =  {
    am: {
        "hi": "Բարև",
        "Home": "Գլխավոր",
        "About": "Մեր Մասին",
        "Plans": "Ծրագրեր",
        "Blog":"Բլոգ",
        "Contact":"Կապ մեզ հետ",
        "JoinUs":"Միացեք մեզ",
        "our_amazing_features": "Մեր բացառիկ առանձնահատկությունները",
        "travel_for_everyone": "Ճանապարհորդություն բոլորի համար",
        "spend_your_money_in_the_right_way":"Ծախսեք ձեր գումարը ճիշտ ճանապարհով",
        "why_choose_us":"Ինչու ընտրել մեզ?",
        "you_can_choose_your_tours_from":"Դուք կարող եք ընտրել Ձեր ուղևորությունը և տանից, և աշխատավայրից, ցանկացած ժամանակ",
        "our_tour_company_can_implement_all_your_imaginations":"Մեր տուրիստական կազմակերպությունը կարող է իրականացնել Ձեր բոլոր պատկերացումները",
        "available_prices":"Մատչելի Գներ",
        "proffesional_service":"Պռոֆեսիոնալ Սպասարկում",
        "secure_relax":"Անվտանգ Հանգիստ",
        "reliable_staff":"Վստահելի Անձնակազմ",
        "picturesque_places":"Գեղատեսիլ Վայրեր",
        "tasty_national_food":"Համեղ Ազգային Սնունդ",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"Ինչ դուք կստանաք մեզ հետ հագստանալու արդյունքում",
        "latest_review":"Վերջին Կարծիքները",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Մեր նպատակն է տեսնել ձեր գնահատականը մեր քրտնաջան աշխատանքի վերաբերյալ",
        "last_reviews":"Վերջին Կարծիքներ",
        "all_reviews":"Բոլոր Կարծիքներ",
        "top_reviews":"Հայտնի Կարծիքներ",
        "name_":"Անուն",
        "date_":"Ամսատիվ",
        "review_":"Կարծիք",
        "rate_":"Գնահատական",
     
    },
    ru: {
        "hi": "Здравствуй",
        "Home": "Главний",
        "About": "О Нас",
        "Plans": "Планы",
        "Blog":"Блог",
        "Contact":"Контакты",
        "JoinUs":"Присоединяться",
        "our_amazing_features": "Наши удивительные особенности",
        "travel_for_everyone": "Путешествия для всех",
        "spend_your_money_in_the_right_way":"Тратьте свои деньги правильно!",
        "why_choose_us":"Почему выбрать нас?",
        "you_can_choose_your_tours_from":"Вы можете выбрать Вашу поездку и из дома,и из места работы в любое время",
        "our_tour_company_can_implement_all_your_imaginations":"Наше туристическое агентство может осуществлять все ваши воображения",
        "available_prices":"Выгодные Цены",
        "proffesional_service":"Профессиональное Обслуживание",
        "secure_relax":"Безопасный Отдых",
        "reliable_staff":"Надежный Коллектив",
        "picturesque_places":"Колоритные Места",
        "tasty_national_food":"Вкусная Национальная Еда",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"Что вы получите отдыхая с нами",
        "latest_review":"Последные Отзывы",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Наша цель увидеть ваши отзывы насчёт нашей тяжёлой работы",
        "last_reviews":"Последние Отзывы",
        "all_reviews":"Все Отзывы",
        "top_reviews":"Топовые Отзывы",
        "name_":"Имя",
        "date_":"Дата",
        "review_":"Отзывы",
        "rate_":"Оценка",
    },
    en: {
        "hi": "Hi",
        "Home": "Home",
        "About": "About",
        "Plans": "Plans",
        "Blog":"Blog",
        "Contact":"Contact",
        "JoinUs":"Join us",
        "our_amazing_features": "OUR AMAZING FEATURES",
        "travel_for_everyone": "travel for everyone",
        "spend_your_money_in_the_right_way": "Spend your money in the right way",
        "why_choose_us":"Why choose us?",
        "you_can_choose_your_tours_from":"You can choose your tours from anywhere eihter from home or work place, at any time",
        "our_tour_company_can_implement_all_your_imaginations":"Our tour company can implement all your imaginations",
        "available_prices":"AVAILABLE PRICES",
        "proffesional_service":"PROFFESIONAL SERVICE",
        "secure_relax":"SECURE RELAX",
        "reliable_staff":"RELIABLE STAFF",
        "picturesque_places":"PICTURESQUE PLACES",
        "tasty_national_food":"TASTY NATIONAL FOOD",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"What you will get as a result of relaxing with us",
        "latest_review":"LATEST REVIEW",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Our goal is to see your rating of our hard work",
        "last_reviews":"LAST REVIEWS",
        "all_reviews":"ALL REVIEWS",
        "top_reviews":"TOP REVIEWS",
        "name_":"Name",
        "date_":"Date",
        "review_":"Review",
        "rate_":"Rate",
        
    }
}

export const selectLanguage = (lang) => languages[lang];
