const languages =  {
    am: {
        "hi": "Բարև",
        "Home": "Գլխավոր",
        "About": "Մեր Մասին",
        "Plans": "Ծրագրեր",
        "Blog":"Բլոգ",
        "Contact":"Կապ մեզ հետ",
        "JoinUs":"Միացեք մեզ",
        "our_amazing_features": "Մեր բացառիկ առանձնահատկությունները",
        "travel_for_everyone": "Ճանապարհորդություն բոլորի համար",
        "contact_us": "Կապ մեզ հետ",
        "get_in_touch": "Եղիր կապի մեջ",
        "please_feel_free_to_contact_us_through_our_support_center": "Դուք կարող եք կապ հաստատել մեր կոնտակտ կենտրոնի հետ",
        "send_us_a_message": "Գրեք մեզ",
        "spend_your_money_in_the_right_way":"Ծախսեք ձեր գումարը ճիշտ ճանապարհով",
        "why_choose_us":"Ինչու ընտրել մեզ?",
        "you_can_choose_your_tours_from":"Դուք կարող եք ընտրել Ձեր ուղևորությունը և տանից, և աշխատավայրից, ցանկացած ժամանակ",
        "our_tour_company_can_implement_all_your_imaginations":"Մեր տուրիստական կազմակերպությունը կարող է իրականացնել Ձեր բոլոր պատկերացումները",
        "available_prices":"Մատչելի Գներ",
        "proffesional_service":"Պռոֆեսիոնալ Սպասարկում",
        "secure_relax":"Անվտանգ Հանգիստ",
        "reliable_staff":"Վստահելի Անձնակազմ",
        "picturesque_places":"Գեղատեսիլ Վայրեր",
        "tasty_national_food":"Համեղ Ազգային Սնունդ",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"Ինչ դուք կստանաք մեզ հետ հագստանալու արդյունքում",
        "latest_review":"Վերջին Կարծիքները",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Մեր նպատակն է տեսնել ձեր գնահատականը մեր քրտնաջան աշխատանքի վերաբերյալ",
        "last_reviews":"Վերջին Կարծիքներ",
        "all_reviews":"Բոլոր Կարծիքներ",
        "top_reviews":"Հայտնի Կարծիքներ",
        "name_":"Անուն",
        "date_":"Ամսատիվ",
        "review_":"Կարծիք",
        "rate_":"Գնահատական",
        "who_we_are":"ՈՎ ԵՆՔ ՄԵՆՔ",
        "about_our_company":"ՄԵՐ ԿԱԶՄԱԿԵՐՊՈՒԹՅԱՆ ՄԱՍԻՆ",
        "comparing_with_tadays_tour_companies_we_have_created_unique_and_officient":"Համեմատվելով այսօրվա տուրիստական կազմակերպությունների հետ` մենք ստեղծել ենք յուրահատուկ և արդյունավետ մոտեցման ձևեր",
        "applying_to_our_tour_company_you_get_rid_of_any_risks_because_we_aim_to_make_your_rest":"Դիմելով մեր տուրիստական կազմակերպությանը դուք ազատվում եք ռիսկերից,քանի որ մենք ձգտում ենք դարձնել Ձեր հանգիստը տարբերվող և առանձնահատուկ:Խոստանում ենք տալ այն ամենը,ինչ ներկայացված է մեր էջում",
        "efficency":"արդյունավետ",
        "experience":"փորձ",
        "security":"անվտանգ",
        "transparency":"թափանցիկություն",
        "simple":"պարզ",
        "compliant":"զիջող",
        "travel_to_armenia":"ճամփորդեք դեպի հայաստան",
        "choose_your_tour":"Ընտրեք Ձեր Հանգիստը",
        "get_the_most_comfortable_and_affordable_tours_with_us":"Ստացեք ամենհարմարավետ և մատչելի հանգիստը,ՄԵԶ ՄՈՏ",
        "choose_tour":"ընտրել հանգիստ",
    },
    ru: {
        "hi": "Здравствуй",
        "Home": "Главний",
        "About": "О Нас",
        "Plans": "Планы",
        "Blog":"Блог",
        "Contact":"Контакты",
        "JoinUs":"Присоединиться",
        "our_amazing_features": "Наши удивительные особенности",
        "travel_for_everyone": "Путешествия для всех",
        "contact_us": "Связаться с нами",
        "get_in_touch": "Будьте на связи",
        "please_feel_free_to_contact_us_through_our_support_center": "Вы можете свободно обращаться к нам через наш центр поддержки",
        "send_us_a_message": "Напишите нам письмо",
        "spend_your_money_in_the_right_way":"Тратьте свои деньги правильно!",
        "why_choose_us":"Почему выбрать нас?",
        "you_can_choose_your_tours_from":"Вы можете выбрать Вашу поездку и из дома,и из места работы в любое время",
        "our_tour_company_can_implement_all_your_imaginations":"Наше туристическое агентство может осуществлять все ваши воображения",
        "available_prices":"Выгодные Цены",
        "proffesional_service":"Профессиональное Обслуживание",
        "secure_relax":"Безопасный Отдых",
        "reliable_staff":"Надежный Коллектив",
        "picturesque_places":"Колоритные Места",
        "tasty_national_food":"Вкусная Национальная Еда",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"Что вы получите отдыхая с нами",
        "latest_review":"Последные Отзывы",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Наша цель увидеть ваши отзывы насчёт нашей тяжёлой работы",
        "last_reviews":"Последние Отзывы",
        "all_reviews":"Все Отзывы",
        "top_reviews":"Топовые Отзывы",
        "name_":"Имя",
        "date_":"Дата",
        "review_":"Отзывы",
        "rate_":"Оценка",
        "who_we_are":"КТО МЫ ТАКИЕ",
        "about_our_company":"ПРО НАШУ КОМПАНИЮ",
        "comparing_with_tadays_tour_companies_we_have_created_unique_and_officient":"Сравнивая сегодняшние турагентства,мы придумали специфические и продуктивные формы подхода",
        "applying_to_our_tour_company_you_get_rid_of_any_risks_because_we_aim_to_make_your_rest":"Обращаясь к нашей тур компании Вы избавляетесь от рисков,потому что мы стремимся сделать Ваш отдых специальным и неповторяющимся.Обещаем обеспечить всем,что представлен на нашей странице",
        "efficency":"продуктивность",
        "experience":"опыт",
        "security":"безопасность",
        "transparency":"прозрачность",
        "simple":"ясный",
        "compliant":"уступающий",
        "travel_to_armenia":"Путешествуйте в Армению",
        "choose_your_tour":"Выбирайте свой тур",
        "get_the_most_comfortable_and_affordable_tours_with_us":"Получите самый удобный и доступный отдых у Нас",
        "choose_tour":"выбрать тур",
    },
    en: {
        "hi": "Hi",
        "Home": "Home",
        "About": "About",
        "Plans": "Plans",
        "Blog":"Blog",
        "Contact":"Contact",
        "JoinUs":"Join us",
        "our_amazing_features": "OUR AMAZING FEATURES",
        "travel_for_everyone": "travel for everyone",
        "contact_us": "Contact us",
        "get_in_touch": "Get in touch",
        "please_feel_free_to_contact_us_through_our_support_center": "Please feel free to contact us through our support center",
        "send_us_a_message": "Send Us a Message",
        "spend_your_money_in_the_right_way": "Spend your money in the right way",
        "why_choose_us":"Why choose us?",
        "you_can_choose_your_tours_from":"You can choose your tours from anywhere eihter from home or work place, at any time",
        "our_tour_company_can_implement_all_your_imaginations":"Our tour company can implement all your imaginations",
        "available_prices":"AVAILABLE PRICES",
        "proffesional_service":"PROFFESIONAL SERVICE",
        "secure_relax":"SECURE RELAX",
        "reliable_staff":"RELIABLE STAFF",
        "picturesque_places":"PICTURESQUE PLACES",
        "tasty_national_food":"TASTY NATIONAL FOOD",
        "what_you_will_get_as_a_result_of_relaxing_with_us":"What you will get as a result of relaxing with us",
        "latest_review":"LATEST REVIEW",
        "our_goal_is_to_see_your_rating_of_our_hard_work":"Our goal is to see your rating of our hard work",
        "last_reviews":"LAST REVIEWS",
        "all_reviews":"ALL REVIEWS",
        "top_reviews":"TOP REVIEWS",
        "name_":"Name",
        "date_":"Date",
        "review_":"Review",
        "rate_":"Rate",
        "who_we_are":"WHO WE ARE",
        "about_our_company":"ABOUT OUR COMPANY",
        "comparing_with_tadays_tour_companies_we_have_created_unique_and_officient":"Comparing with today`s tour companies we have created unique and efficient ways of approach",
        "applying_to_our_tour_company_you_get_rid_of_any_risks_because_we_aim_to_make_your_rest":"Applying to our tour company You get rid of any risks,because we aim to make your rest different and unique.We promise to give you everiting introduced in our page",
        "efficency":"efficency",
        "experience":"experience",
        "security":"security",
        "transparency":"transparency",
        "simple":"simple",
        "compliant":"compliant",
        "travel_to_armenia":"travel to armenia",
        "choose_your_tour":"Choose Your Tour",
        "get_the_most_comfortable_and_affordable_tours_with_us":"Get the most Comfortable and Affordable tours With Us",
        "choose_tour":"choose tour",
    }
}

export const selectLanguage = (lang) => languages[lang];
